config/routes.rb
Ganban::Application.routes.draw do
  resources :documents

  resources :profiles

  resources :checklists do
    put :done, on: :member
  end

  resources :comments

  resources :cards, except: [:new, :edit] do
    put :move, on: :member
  end

  resources :lists do
    put :move, on: :member
  end

  resources :current_projects, only: [:create]

  resources :projects do
    get :users, on: :member
    get :auto_users, on: :collection
  end

  resources :collaborators, only: [:index, :create, :destroy]

  devise_for :admins, controllers: {sessions: 'hq/sessions'}, path: 'hq',
             path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret',
                          confirmation: 'verification'}
  devise_for :users,
             path: 'accounts',
             controllers: {registrations: 'registrations', sessions: 'sessions',},
             path_names: {sign_in: 'login', sign_up: 'new', sign_out: 'logout', password: 'secret',
                          confirmation: 'verification'}
  root to: 'welcome#index'
  namespace :hq do
      resources :dashboard, only: [:index]
  end

  resources :agent_sessions, only: :create

  resources :dashboard, only: [:index]

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  belongs_to :assigned, class_name: 'User', foreign_key: 'assignment_id'
  has_many :comments
  has_many :checklists
  has_many :documents

  scope :by_assigned, lambda {|user_id|
    where(assignment_id: user_id)
  }

  scope :by_created, lambda {|user_id|
    where(owner_id: user_id)
  }

  validates :title, presence: true
  validates :list_id, presence: true
  validates :sort, uniqueness: {scope: :list_id}

  before_create :set_sort

  validates_inclusion_of :assignment_id, :in => lambda { |card| card.list.project.users.map(&:id) }, allow_nil: true

  private
  def set_sort
    last_card = self.list.cards.order('sort ASC').last
    self.sort = last_card.present? ? last_card.sort + 1 : 1
  end

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  belongs_to :card
  validates_presence_of :title
end

app/models/checklist_observer.rb
class ChecklistObserver < ActiveRecord::Observer
  def after_create(checklist)
    card = checklist.card
    card.checklist_total_count = card.checklist_total_count + 1
    card.save!

  end

  def after_update(checklist)
    card = checklist.card
    if checklist.done?
      card.checklist_done_count = card.checklist_done_count + 1
    else
      card.checklist_done_count = card.checklist_done_count - 1
    end
    card.save!
  end

  def after_destroy(checklist)
    card = checklist.card
    card.checklist_total_count = card.checklist_total_count - 1
    if checklist.done?
      card.checklist_done_count = card.checklist_done_count - 1
    end
    card.save!
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :card
  belongs_to :user

  validates_presence_of :body
end

app/models/comment_observer.rb
class CommentObserver < ActiveRecord::Observer
  def after_create(comment)
    card = comment.card
    card.comment_count = card.comment_count + 1
    card.save!
  end

  def after_destroy(comment)
    card = comment.card
    card.comment_count = card.comment_count - 1
    card.save!
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :card
  belongs_to :user

  has_attached_file :file,
      :storage => :s3,
      :s3_protocol => 'http',
      :s3_host_name => AWS_CONFIG["end_point"],
      :s3_credentials => "#{Rails.root}/config/application.yml",
      :url => ":s3_alias_url",
      :s3_host_alias => AWS_CONFIG["aws_raw_url"],
      :path => "files/:id/:style/:file_name.:extension"
  validates_attachment_size :file, less_than: 3.megabytes

  Paperclip.interpolates :file_name do |attachment, style|
    attachment.instance.normalized_file_name
  end

  def normalized_file_name
    "#{card.id}-#{file_file_name.split('.')[0]}-#{id}"
  end
end

app/models/document_observer.rb
class DocumentObserver < ActiveRecord::Observer
  def after_create(document)
    card = document.card
    card.document_count += 1
    card.save
  end

  def after_destroy(document)
    card = document.card
    card.document_count -= 1
    card.save
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :project
  has_many :cards, dependent: :destroy

  validates :name, presence: true, uniqueness: {scope: :project_id}
  validates :sort, uniqueness: {scope: :project_id}

  before_create :set_sort
  private
  def set_sort
    last_list = self.project.lists.order('sort ASC').last
    self.sort = last_list.present? ? last_list.sort + 1 : 1
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :users

  has_many :lists, dependent: :destroy
  has_many :cards, through: :lists

  accepts_nested_attributes_for :lists, allow_destroy: true

  scope :by_owner, lambda { |owner_id| where(owner_id: owner_id) unless owner_id.nil? }

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email
  #has_many :projects, foreign_key: 'owner_id'
  has_many :own_projects, class_name: 'Project', foreign_key: 'owner_id'
  has_and_belongs_to_many :projects
  has_many :comments
  has_many :documents

  has_one :profile
  delegate :name, :name=, :github, :github=, :stackoverflow, :stackoverflow=, :bio, :bio=, :facebook, :facebook=, :twitter, :twitter=, :blog, :blog=, to: :profile

  has_many :domains

  accepts_nested_attributes_for :profile

  def assigned_to_you(current_project)
    current_project.cards.where(assignment_id: self.id).count
  end

  def created_by_you(current_project)
    current_project.cards.where(owner_id: self.id).count
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def avatar_url(user)
    if user
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png"
    else
      'http://placehold.it/75x75&text=User'
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/welcome/index.html.haml
- title t 'welcome'

.jumbotron.text-center
  .row
    .col-md-7
      %h1 Ganban is a simple Kanban application

      %hr/

      - if current_user
        .row-fluid.marketing
          %p
            %strong Name:
            = current_user.name
            %br/
            %strong Email:
            = current_user.email
        - if @current_project
          = link_to 'Ganban Dashboard', @current_project, class: 'btn btn-lg btn-primary'
        - else
          = link_to 'Ganban Dashboard', new_project_path, class: 'btn btn-lg btn-primary'
      - else
        .sign-buttons
          = link_to 'Create your Kanban now!', new_user_registration_path, class: 'btn btn-lg btn-success'
          = link_to 'Sign in', new_user_session_path, class: 'btn btn-lg btn-primary'
        = link_to 'You can sign in as guest user from here<br/>(if you are in Rails Rumble Team)'.html_safe, agent_sessions_path(user_id: @guest_user.id), method: :post, class: 'sml-link'
    .col-md-5
      #preview
        =image_tag '0-ganban-preview.jpg'

.row
  .col-md-10.col-md-offset-1
    %p
      %h3 What is Kanban?
      %strong Kanban (かんばん(看板)?) (literally signboard or billboard)
      is a scheduling system for lean and just-in-time (JIT)
      production.Kanban is a system to control the logistical chain from a production point of view,
      and is not an inventory control system. Kanban was developed by Taiichi Ohno, at Toyota,
      to find a system to improve and maintain a high level of production.
      Kanban is one method through which JIT is achieved.


#videos
  %h3.text-center See how it works
  %hr/
  .row
    .col-md-3
      =link_to 'http://vimeo.com/77360714', target: :blank do
        =image_tag '1-create-project.jpg'
        .text-center
          Create project
    .col-md-3
      =link_to 'https://vimeo.com/77360715', target: :blank do
        =image_tag '2-add-project-collaborators.jpg'
        .text-center
          Add project collaborators
    .col-md-3
      =link_to 'https://vimeo.com/77360716', target: :blank do
        =image_tag '3-user-kanban.jpg'
        .text-center
          Use kanban
    .col-md-3
      =link_to 'https://vimeo.com/77361295', target: :blank do
        =image_tag '4-add-card-to-kanban.jpg'
        .text-center
          Add cards to kanban
  .row
    .col-md-3.col-md-offset-3
      =link_to 'http://vimeo.com/77361852', target: :blank do
        =image_tag '5-card-detail.jpg'
        .text-center
          Card detail
    .col-md-3
      =link_to 'http://vimeo.com/77362348', target: :blank do
        =image_tag '6-assign-card.jpg'
        .text-center
          Assign Card (Task)
    -#.col-md-3
    -#  =link_to '#', target: :blank do
    -#    =image_tag 'http://placehold.it/300x200&text=Screencast video', class: 'thumbnail'
    -#    .text-center
    -#      Use kanban
    -#.col-md-3
    -#  =link_to '#', target: :blank do
    -#    =image_tag 'http://placehold.it/300x200&text=Screencast video', class: 'thumbnail'
    -#    .text-center
    -#      Profile & Account