config/routes.rb
Ganban::Application.routes.draw do
  resources :documents

  resources :profiles

  resources :checklists do
    put :done, on: :member
  end

  resources :comments

  resources :cards, except: [:new, :edit] do
    put :move, on: :member
  end

  resources :lists do
    put :move, on: :member
  end

  resources :current_projects, only: [:create]

  resources :projects do
    get :users, on: :member
    get :auto_users, on: :collection
  end

  resources :collaborators, only: [:index, :create, :destroy]

  devise_for :admins, controllers: {sessions: 'hq/sessions'}, path: 'hq',
             path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret',
                          confirmation: 'verification'}
  devise_for :users,
             path: 'accounts',
             controllers: {registrations: 'registrations', sessions: 'sessions',},
             path_names: {sign_in: 'login', sign_up: 'new', sign_out: 'logout', password: 'secret',
                          confirmation: 'verification'}
  root to: 'welcome#index'
  namespace :hq do
      resources :dashboard, only: [:index]
  end

  resources :agent_sessions, only: :create

  resources :dashboard, only: [:index]

  

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  belongs_to :assigned, class_name: 'User', foreign_key: 'assignment_id'
  has_many :comments
  has_many :checklists
  has_many :documents

  scope :by_assigned, lambda {|user_id|
    where(assignment_id: user_id)
  }

  scope :by_created, lambda {|user_id|
    where(owner_id: user_id)
  }

  validates :title, presence: true
  validates :list_id, presence: true
  validates :sort, uniqueness: {scope: :list_id}

  before_create :set_sort

  validates_inclusion_of :assignment_id, :in => lambda { |card| card.list.project.users.map(&:id) }, allow_nil: true

  private
  def set_sort
    last_card = self.list.cards.order('sort ASC').last
    self.sort = last_card.present? ? last_card.sort + 1 : 1
  end

end

app/controllers/cards_controller.rb
# encoding: UTF-8
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def show
    add_breadcrumb @card.list.project.name, project_path(@card.list.project)
    add_breadcrumb "Card ##{@card.id}", card_path(@card)
    @collaborators = @card.list.project.users
    @checklist_percentage = get_percentage(@card)
    respond_with(@card)
  end


  def create
    @card = Card.new(card_params)
    @card.owner_id = current_user.id
    @card.save
    respond_to do |format|
      format.js
    end
  end

  def update
    #raise Exception
    if params[:list_change]
      list = List.find(params[:card][:list_id])
      if list.cards.count > 0
        @card.sort= list.cards.last.sort+1
      else
        @card.sort = 1
      end
      @card.list_id = list.id
      @card.save
    else
      @card.update(card_params)
    end
    respond_to do |format|
      format.html { redirect_to(card_path(@card)) }
      format.js
      format.json{ render json: @card}
    end
  end

  def destroy
    @card_id = @card.id
    @card.destroy
    respond_to do |format|
      format.js
    end
  end

  def move
    @current_list = List.find(params[:list])
    @current_card = Card.find(params[:id])
    @current_card.sort = 0
    @current_card.list = @current_list
    @current_card.save
    @cards = @current_list.cards
    sort = Array.new
    params[:sort].each do |hash|
      sort << hash.to_i
    end
    @cards.each_with_index do |card,index|
      card.sort = index*100
      card.save
    end

    @cards.each do |card|
      card.sort = (sort.index(card.id))+1
      card.save
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def set_card
    @card = @current_project.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:assignment_id, :body, :done, :due_date, :list_id, :private, :sort, :title)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_blank.html.haml
%h1 Your blank message here

app/views/cards/_card.html.haml
- if card.id.present?
  .card.droppable{id: "#{card.id}-card"}
    = link_to '×', card_path(card), method: :delete, class: 'close', data: { toggle: 'tooltip' }, title: 'Remove Card', remote: true, confirm: 'Are you sure?'
    %p.title
      =link_to(truncate(card.title), card)
    .card-stats.card-stats-inline
      %span.stat{data: {toggle: 'tooltip'}, title: 'Checklists'}
        %i.icon-list
        = card.try(:checklist_done_count).to_s + '/' + card.try(:checklist_total_count).to_s
      %span.stat{data: {toggle: 'tooltip'}, title: 'Comments'}
        %i.icon-comments-alt
        = card.try(:comment_count)
      %span.stat{data: {toggle: 'tooltip'}, title: 'Attachments'}
        %i.icon-file-alt
        = card.try(:document_count)
      - if card.due_date.present?
        %span.stat{data: {toggle: 'tooltip'}, title: card.due_date < Date.current ? 'Past due date' : 'Due date', class: card.due_date < Date.current ? 'past_due' : ''}
          %i.icon-time
          = card.due_date.to_formatted_s(:short)
    .user
      - if card.assigned.present?
        = image_tag avatar_url(card.assigned), class: 'img-circle avatar-image avatar-image-md', data: {toggle: 'tooltip'}, title: card.try(:assigned).try(:name)
      - else
        = image_tag 'empty-collaborator.png', class: 'img-circle avatar-image avatar-image-md avatar-image-empty'

app/views/cards/_filters.html.haml
.table-header.row
  .col-lg-9
    TODO: Add filters here
  .col-lg-3
    = search_form_for @search, builder: SimpleForm::FormBuilder do |f|
      .input-group
        = f.input_field :owner_id_or_assignment_id_or_list_or_title_or_body_or_due_date_or_done_or_comment_count_or_document_count_or_checklist_total_count_or_checklist_done_count_or_private_or_sort_cont, label: false, input_html: {class: 'form-control'}, placeholder: 'Quick search...'
        %span.input-group-btn
          = button_tag( class: 'btn') do
            %i.icon-search

app/views/cards/_form.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title
  .panel-body
    = simple_form_for(@card) do |f|
      = f.error_notification

      .form-inputs
        = f.input :assignment_id
        = f.association :list
        = f.input :title
        = f.input :body
        = f.input :due_date
        = f.input :done
        = f.input :private

      .form-actions
        = f.button :submit, class: 'btn btn-default'
        = link_to t('cancel'), cards_path, class: 'btn'

app/views/cards/_list.html.haml
.panel-heading
  %i.icon-table.icon-large
  = t('tt.index', resource_name: Card.model_name.human)
  .panel-tools
    .btn-group
      %a.btn{href: '#'}
        %i.icon-wrench
        Settings
      %a.btn{href: '#'}
        %i.icon-filter
        Filters
      %a.btn{href: cards_path, data: {toggle: 'toolbar-tooltip'}, title: 'Reload'}
        %i.icon-refresh
    .badge= @cards.total_entries
.panel-body.filters
  = render 'filters'
%table.table
  %thead
    %tr
      %th #
      %th= sort_link(@search, :owner_id, t('activerecord.attributes.card.owner_id'))
      %th= sort_link(@search, :assignment_id, t('activerecord.attributes.card.assignment_id'))
      %th= sort_link(@search, :list, t('activerecord.attributes.card.list'))
      %th= sort_link(@search, :title, t('activerecord.attributes.card.title'))
      %th= sort_link(@search, :body, t('activerecord.attributes.card.body'))
      %th= sort_link(@search, :due_date, t('activerecord.attributes.card.due_date'))
      %th= sort_link(@search, :done, t('activerecord.attributes.card.done'))
      %th= sort_link(@search, :comment_count, t('activerecord.attributes.card.comment_count'))
      %th= sort_link(@search, :document_count, t('activerecord.attributes.card.document_count'))
      %th= sort_link(@search, :checklist_total_count, t('activerecord.attributes.card.checklist_total_count'))
      %th= sort_link(@search, :checklist_done_count, t('activerecord.attributes.card.checklist_done_count'))
      %th= sort_link(@search, :private, t('activerecord.attributes.card.private'))
      %th= sort_link(@search, :sort, t('activerecord.attributes.card.sort'))
      %th.actions
        Actions
  %tbody
    = render @cards

app/views/cards/create.js.erb
$("#list-<%= @card.list_id %>").html("<%= escape_javascript( render @card.list.cards.order('sort asc') ) %>");
$("#list-<%= @card.id %>-title-input").val('');
$("#<%= @card.id %>-card").effect('highlight');
$("#list-<%= @card.list_id %>-title-input").val("");

$(function() {
    $(".draggable").draggable({
        containment: "#wrapper",
        revert: "invalid"
    });
    return $(".droppable").droppable({
        tolerance: "fit",
        over: function(event, ui) {
            return $(".ui-dragable-dragging").addClass("hoverClass");
        },
        out: function(event, ui) {
            return $(".ui-dragable-dragging").removeClass("hoverClass");
        },
        drop: function(event, ui) {
            var URL, assigned_id, card, card_id, main_cont, new_user, new_user_img;
            new_user = ui.draggable;
            card_id = $(this).attr('id');
            new_user_img = ui.draggable.attr('src');
            assigned_id = ui.draggable.attr('id');
            main_cont = $(this).find('.img-circle');
            main_cont.attr('src', new_user_img);
            new_user.attr('style', 'position: relative;');
            ui.draggable.remove();
            URL = "/cards/" + card_id + '.js';
            card = {
                card: {
                    assignment_id: assigned_id
                }
            };
            $.ajax({
                url: URL,
                type: "PUT",
                data: JSON.stringify(card),
                contentType: "application/json",
                success: function(result) {}
            });
            return $('#assign-project-collaborators').prepend($(new_user));
        }
    });
});

app/views/cards/destroy.js.erb
$("#<%= @card_id %>-card").fadeOut('fast', function() {
  $(this).remove();
});

$(function() {
    $(".draggable").draggable({
        containment: "#wrapper",
        revert: "invalid"
    });
    return $(".droppable").droppable({
        tolerance: "fit",
        over: function(event, ui) {
            return $(".ui-dragable-dragging").addClass("hoverClass");
        },
        out: function(event, ui) {
            return $(".ui-dragable-dragging").removeClass("hoverClass");
        },
        drop: function(event, ui) {
            var URL, assigned_id, card, card_id, main_cont, new_user, new_user_img;
            new_user = ui.draggable;
            card_id = $(this).attr('id');
            new_user_img = ui.draggable.attr('src');
            assigned_id = ui.draggable.attr('id');
            main_cont = $(this).find('.img-circle');
            main_cont.attr('src', new_user_img);
            new_user.attr('style', 'position: relative;');
            ui.draggable.remove();
            URL = "/cards/" + card_id + '.js';
            card = {
                card: {
                    assignment_id: assigned_id
                }
            };
            $.ajax({
                url: URL,
                type: "PUT",
                data: JSON.stringify(card),
                contentType: "application/json",
                success: function(result) {}
            });
            return $('#assign-project-collaborators').prepend($(new_user));
        }
    });
});

app/views/cards/index.html.haml
- content_for :toolbar do
  = link_to new_card_path, class: 'btn btn-default' do
    %i.icon-plus
    = t('action_button.new', resource_name: Card.model_name.human)

.panel.panel-default.grid
  =blankable(@cards)
  .panel-footer
    .pagination.pagination-sm
      = will_paginate @cards, renderer: BootstrapPagination::Rails, bootstrap: 3

app/views/cards/move.js.erb
$("#<%= @current_card.id %>-card").effect('highlight');

$(function() {
    $(".draggable").draggable({
        containment: "#wrapper",
        revert: "invalid"
    });
    return $(".droppable").droppable({
        tolerance: "fit",
        over: function(event, ui) {
            return $(".ui-dragable-dragging").addClass("hoverClass");
        },
        out: function(event, ui) {
            return $(".ui-dragable-dragging").removeClass("hoverClass");
        },
        drop: function(event, ui) {
            var URL, assigned_id, card, card_id, main_cont, new_user, new_user_img;
            new_user = ui.draggable;
            card_id = $(this).attr('id');
            new_user_img = ui.draggable.attr('src');
            assigned_id = ui.draggable.attr('id');
            main_cont = $(this).find('.img-circle');
            main_cont.attr('src', new_user_img);
            new_user.attr('style', 'position: relative;');
            ui.draggable.remove();
            URL = "/cards/" + card_id + '.js';
            card = {
                card: {
                    assignment_id: assigned_id
                }
            };
            $.ajax({
                url: URL,
                type: "PUT",
                data: JSON.stringify(card),
                contentType: "application/json",
                success: function(result) {}
            });
            return $('#assign-project-collaborators').prepend($(new_user));
        }
    });
});

app/views/cards/show.html.haml
- title 'Card - ' + @card.title
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = t('tt.show', resource_name: Card.model_name.human)
  .panel-body
    .row
      .col-md-9
        %p
          %strong= best_in_place @card, :title, activator: '#card-title-edit-activator'
          %a#card-title-edit-activator.inplace-edit-activator{href: '#'}
            %i.icon-edit
            Edit title...
        %p
          = best_in_place @card, :body, type: :textarea, :display_with => lambda { |v| v.gsub(/\n/, '<br/>').html_safe }, activator: '#card-body-edit-activator'
          %a#card-body-edit-activator.inplace-edit-activator{href: '#'}
            %i.icon-edit
            Edit description...

        %hr/

        #checklist_form
          #progress-check-list
            %h4
              %i.icon-list-alt
              Checklists
              %span#checklist_percentage.pull-right.label.label-info.sml-text="#{@checklist_percentage} % Complete"
            .progress
              .progress-bar.progress-bar-info{'aria-valuemax' => '100', 'aria-valuemin' => '0', 'aria-valuenow' => @checklist_percentage, role: 'progressbar', style: "width: #{@checklist_percentage}%;"}
                %span.sr-only
                  ="#{@checklist_percentage}% Completed"

          = render 'checklists/form'
          #checklists
            = render @card.checklists

        %hr/
        #comments
          %h4
            %i.icon-comments-alt
            Comments
          = render @card.comments
        #comment_form
          = render 'comments/form'

      .col-md-3
        .panel.panel-default.panel-light
          .panel-body
            .text-center
              #assigned_id
                = image_tag avatar_url(@card.assigned), class: 'pointer card-collaborator-edit-activator img-circle avatar-image'
              %p
                %strong.card-collaborator-edit-activator= best_in_place @card, :assignment_id, type: :select, classes: 'assign_best_in_place', nil: '<span></span>', collection: @collaborators.map{|u| [u.id, u.name]}, activator: '.card-collaborator-edit-activator'
                %br/
                %a.card-collaborator-edit-activator.inplace-edit-activator{href: '#'}
                  %i.icon-edit
                  Change collaborator...
                - if @card.assigned.present?
                  %br/
                  = link_to card_path(@card, card: {assignment_id: nil}), class: 'inplace-edit-activator', method: :put, remote: true do
                    %i.icon-remove-circle
                    Remove assigned...
            %hr/

            #list-switcher.btn-group{data: {toggle: 'tooltip'}, title: 'Swtich list'}
              %button.btn.btn-primary.dropdown-toggle{'data-toggle' => 'dropdown', type: 'button'}
                = @card.list.name
                %span.caret
              %ul.dropdown-menu{role: 'menu'}
                - @current_project.lists.each do |list|
                  - if @card.list.id != list.id
                    %li
                      = link_to list.name, card_path(@card, card: {list_id: list.id}, list_change: true), method: :put


            .card-stats.card-stats-lg
              %span.stat
                %strong{class: (@card.due_date.present? && @card.due_date < Date.current) ? 'past_due_text' : ''}
                  %i.icon-time
                  = best_in_place @card, :due_date, type: :date, activator: '.card-due_date-edit-activator'
                %a.pull-right.card-due_date-edit-activator.inplace-edit-activator{href: '#'}
                  %i.icon-edit
                  Set...

              %span#checklist_stat.stat
                %strong
                  %i.icon-list
                  = @card.try(:checklist_done_count).to_s + '/' + @card.try(:checklist_total_count).to_s
                Checklist(s)

              %span#comment_stat.stat
                %strong
                  %i.icon-comments-alt
                  = @card.try(:comment_count)
                Comment(s)

              %span.stat
                %strong#document-count
                  %i.icon-file-alt
                  = @card.try(:document_count)
                Document(s)
                %a.pull-right.inplace-edit-activator{href: '#documentsModal', data: {toggle: 'modal'}}
                  %i.icon-plus-sign
                  Add...
                %table#documents-list-table.table.table-condensed
                  %tbody#documents-list-table-body
                    - @card.documents.each do |attachment|
                      %tr{id: "document-#{attachment.id}"}
                        %td= link_to(truncate(attachment.file_file_name, length: 20), attachment.file.url, target: '_blank')
                        %td= number_to_human_size(attachment.file_file_size)
                        %td
                          = link_to document_path(attachment), method: :delete, remote: true, confirm: 'Are you sure?',
                            class: 'inplace-edit-activator', data: {toggle: 'tooltip'}, title: 'Remove' do
                            %i.icon-remove-circle



#documentsModal.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', role: 'dialog', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'modal', type: 'button'} ×
        %h4.modal-title Attach more documents
      .modal-body
        = form_for Document.new, multipart: true, html: {class: :dropzone, id: 'photo-dropzone'} do |f|
          = f.hidden_field :file
          = f.hidden_field :card_id, value: @card.id
      .modal-footer
        %button#btn-close.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close

app/views/cards/update.js.erb
$("#assigned_id").html("<%= escape_javascript( image_tag avatar_url(@card.assigned), class: 'pointer card-collaborator-edit-activator img-circle avatar-image' ) %>");
$("#best_in_place_card_<%= @card.id %>_assignment_id").html("");
$("#<%= @card.id %>-card").effect('highlight');
$(function() {
    $(".draggable").draggable({
        containment: "#wrapper",
        revert: "invalid"
    });
    return $(".droppable").droppable({
        tolerance: "fit",
        over: function(event, ui) {
            return $(".ui-dragable-dragging").addClass("hoverClass");
        },
        out: function(event, ui) {
            return $(".ui-dragable-dragging").removeClass("hoverClass");
        },
        drop: function(event, ui) {
            var URL, assigned_id, card, card_id, main_cont, new_user, new_user_img;
            new_user = ui.draggable;
            card_id = $(this).attr('id');
            new_user_img = ui.draggable.attr('src');
            assigned_id = ui.draggable.attr('id');
            main_cont = $(this).find('.img-circle');
            main_cont.attr('src', new_user_img);
            new_user.attr('style', 'position: relative;');
            ui.draggable.remove();
            URL = "/cards/" + card_id + '.js';
            card = {
                card: {
                    assignment_id: assigned_id
                }
            };
            $.ajax({
                url: URL,
                type: "PUT",
                data: JSON.stringify(card),
                contentType: "application/json",
                success: function(result) {}
            });
            return $('#assign-project-collaborators').prepend($(new_user));
        }
    });
});